package org.atomnuke.syslog.parser;

/**
 * @author zinic
 */
public enum SyslogParserState {

   START,
   MESSAGE_OCTET_COUNT,
   PRIORITY,
   VERSION,
   TIMESTAMP_HEAD,
   TIMESTAMP_CONTENT,
   HOSTNAME_HEAD,
   HOSTNAME_CONTENT,
   APPNAME_HEAD,
   APPNAME_CONTENT,
   PROCESS_ID_HEAD,
   PROCESS_ID_CONTENT,
   MESSAGE_ID_HEAD,
   MESSAGE_ID_CONTENT,
   STRUCTURED_DATA_HEAD,
   STRUCTURED_DATA_BODY,
   STRUCTURED_DATA_ID,
   STRUCTURED_DATA_PARAM,
   STRUCTURED_DATA_PARAM_NAME,
   STRUCTURED_DATA_PARAM_VALUE,
   MESSAGE_CONTENT,
   STOP,
   ERROR
}
